import { CreateSeriesDto } from '../dto';

export const seriesSeeds: CreateSeriesDto[] = [
  {
    adult: false,
    genreIds: [18, 80],
    idNumber: 1396,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Breaking Bad',
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    popularity: 422.169,
    firstAirDate: '2008-01-20',
    name: 'Breaking Bad',
    voteAverage: 8.894,
    voteCount: 12647,
  },
  {
    adult: false,
    genreIds: [16, 18, 10765, 10759],
    idNumber: 94605,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Arcane',
    overview:
      'AmidNumber the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sidNumberes of a war between magic technologies and clashing convictions.',
    popularity: 93.725,
    firstAirDate: '2021-11-06',
    name: 'Arcane',
    voteAverage: 8.7,
    voteCount: 3426,
  },
  {
    adult: false,

    genreIds: [10759, 35, 16],
    idNumber: 37854,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'ワンピース',
    overview:
      'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decidNumberes to follow in the footsteps of his idNumberol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
    popularity: 162.281,
    firstAirDate: '1999-10-20',
    name: 'One Piece',
    voteAverage: 8.723,
    voteCount: 4166,
  },
  {
    adult: false,

    genreIds: [16, 35, 10765, 10759],
    idNumber: 60625,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Rick and Morty',
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    popularity: 1282.049,
    firstAirDate: '2013-12-02',
    name: 'Rick and Morty',
    voteAverage: 8.7,
    voteCount: 8782,
  },
  {
    adult: false,

    genreIds: [18, 10751],
    idNumber: 70785,
    originCountry: ['CA'],
    originalLanguage: 'en',
    originalName: 'Anne with an E',
    overview:
      'A coming-of-age story about an outsidNumberer who, against all odds and numerous challenges, fights for love and acceptance and for her place in the world. The series centers on a young orphaned girl in the late 1890’s, who, after an abusive childhood spent in orphanages and the homes of strangers, is mistakenly sent to live with an elderly woman and her aging brother. Over time, 13-year-old Anne will transform their lives and eventually the small town in which they live with her unique spirit, fierce intellect and brilliant imagination.',
    popularity: 93.108,
    firstAirDate: '2017-03-19',
    name: 'Anne with an E',
    voteAverage: 8.694,
    voteCount: 4412,
  },
  {
    adult: false,

    genreIds: [10759, 16, 10765],
    idNumber: 31911,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: '鋼の錬金術師 FULLMETAL ALCHEMIST',
    overview:
      'Disregard for alchemy’s laws ripped half of Ed Elric’s limbs from his body and left Al’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric’s course, but their purpose will remain unchanged and their bond unbreakable.',
    popularity: 115.005,
    firstAirDate: '2009-04-05',
    name: 'Fullmetal Alchemist: Brotherhood',
    voteAverage: 8.694,
    voteCount: 1795,
  },
  {
    adult: false,

    genreIds: [16, 10759, 10765],
    idNumber: 246,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Avatar: The Last Airbender',
    overview:
      'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
    popularity: 97.788,
    firstAirDate: '2005-02-21',
    name: 'Avatar: The Last Airbender',
    voteAverage: 8.7,
    voteCount: 3556,
  },
  {
    adult: false,

    genreIds: [16, 10759, 10765],
    idNumber: 85937,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: '鬼滅の刃',
    overview:
      'It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko, the sole survivor, has been transformed into a demon herself. Though devastated by this grim reality, Tanjiro resolves to become a “demon slayer” so that he can turn his sister back into a human, and kill the demon that massacred his family.',
    popularity: 93.17,
    firstAirDate: '2019-04-06',
    name: 'Demon Slayer: Kimetsu no Yaiba',
    voteAverage: 8.682,
    voteCount: 5715,
  },
  {
    adult: false,

    genreIds: [16, 10765, 10759, 18],
    idNumber: 95557,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Invincible',
    overview:
      'Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet. Shortly after his seventeenth birthday, Mark begins to develop powers of his own and enters into his father’s tutelage.',
    popularity: 822.277,
    firstAirDate: '2021-03-25',
    name: 'Invincible',
    voteAverage: 8.671,
    voteCount: 3860,
  },
  {
    adult: false,

    genreIds: [16, 10765, 10759],
    idNumber: 1429,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: '進撃の巨人',
    overview:
      'Several hundred years ago, humans were nearly exterminated by Titans. Titans are typically several stories tall, seem to have no intelligence, devour human beings and, worst of all, seem to do it for the pleasure rather than as a food source. A small percentage of humanity survived by walling themselves in a city protected by extremely high walls, even taller than the biggest Titans. Flash forward to the present and the city has not seen a Titan in over 100 years. Teenage boy Eren and his foster sister Mikasa witness something horrific as the city walls are destroyed by a Colossal Titan that appears out of thin air. As the smaller Titans flood the city, the two kidNumbers watch in horror as their mother is eaten alive. Eren vows that he will murder every single Titan and take revenge for all of mankind.',
    popularity: 200.317,
    firstAirDate: '2013-04-07',
    name: 'Attack on Titan',
    voteAverage: 8.665,
    voteCount: 5676,
  },
  {
    adult: false,

    genreIds: [10759, 16],
    idNumber: 65930,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: '僕のヒーローアカデミア',
    overview:
      'A superhero-admiring boy without any powers enrolls in a prestigious hero academy and learns what it really means to be a hero.',
    popularity: 44.552,
    firstAirDate: '2016-04-03',
    name: 'My Hero Academia',
    voteAverage: 8.663,
    voteCount: 4548,
  },
  {
    adult: false,

    genreIds: [18],
    idNumber: 87108,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Chernobyl',
    overview:
      'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accidNumberent at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
    popularity: 96.227,
    firstAirDate: '2019-05-06',
    name: 'Chernobyl',
    voteAverage: 8.654,
    voteCount: 5490,
  },
  {
    adult: false,

    genreIds: [18, 10765, 35],
    idNumber: 67915,
    originCountry: ['KR'],
    originalLanguage: 'ko',
    originalName: '쓸쓸하고 찬란하神-도깨비',
    overview:
      'In his quest for a bridNumbere to break his immortal curse, a 939-year-old guardian of souls meets a grim reaper and a sprightly student with a tragic past.',
    popularity: 79.054,
    firstAirDate: '2016-12-02',
    name: 'Goblin',
    voteAverage: 8.652,
    voteCount: 2555,
  },
  {
    adult: false,

    genreIds: [80, 18],
    idNumber: 60059,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Better Call Saul',
    overview:
      'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongsidNumbere, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
    popularity: 248.451,
    firstAirDate: '2015-02-08',
    name: 'Better Call Saul',
    voteAverage: 8.652,
    voteCount: 4482,
  },
  {
    adult: false,

    genreIds: [16, 35],
    idNumber: 31132,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Regular Show',
    overview:
      'Two bored groundskeepers, Mordecai (a six-foot-tall blue jay) and Rigby (a hyperactive raccoon) are best friends who spend their days trying to entertain themselves by any means necessary, much to the displeasure of their boss. Their everyday pursuits often lead to things spiraling out of control and into the surreal.',
    popularity: 309.9,
    firstAirDate: '2010-09-06',
    name: 'Regular Show',
    voteAverage: 8.648,
    voteCount: 1806,
  },
  {
    adult: false,

    genreIds: [18],
    idNumber: 100088,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'The Last of Us',
    overview:
      'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.',
    popularity: 208.901,
    firstAirDate: '2023-01-15',
    name: 'The Last of Us',
    voteAverage: 8.643,
    voteCount: 4219,
  },
  {
    adult: false,

    genreIds: [16, 10765, 18, 10759, 35],
    idNumber: 92685,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'The Owl House',
    overview:
      "An animated fantasy-comedy series that follows Luz, a self-assured teenage girl who accidNumberentally stumbles upon a portal to a magical world where she befriends a rebellious witch, Eda, and an adorably tiny warrior, King. Despite not having magical abilities, Luz pursues her dream of becoming a witch by serving as Eda's apprentice at the Owl House and ultimately finds a new family in an unlikely setting.",
    popularity: 160.734,
    firstAirDate: '2020-01-10',
    name: 'The Owl House',
    voteAverage: 8.64,
    voteCount: 1398,
  },
  {
    adult: false,

    genreIds: [35, 10751],
    idNumber: 72637,
    originCountry: ['AR'],
    originalLanguage: 'es',
    originalName: 'O11CE',
    overview:
      'The series revolves around Gabo, a soccer-loving teenager who, upon receiving a scholarship from the prestigious Sports Academic Institute (IAD) of Buenos Aires, will see his dream of playing at Los Halcones Dorados, the renowned amateur team of the school, and also his longing to become a professional footballer.',
    popularity: 118.927,
    firstAirDate: '2017-06-19',
    name: 'Once',
    voteAverage: 8.64,
    voteCount: 1372,
  },
  {
    adult: false,

    genreIds: [16, 9648, 10765],
    idNumber: 13916,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'DEATH NOTE',
    overview:
      'Light Yagami is an ace student with great prospects—and he’s bored out of his mind. But all that changes when he finds the Death Note, a notebook dropped by a rogue Shinigami death god. Any human whose name is written in the notebook dies, and Light has vowed to use the power of the Death Note to ridNumber the world of evil. But will Light succeed in his noble goal, or will the Death Note turn him into the very thing he fights against?',
    popularity: 95.342,
    firstAirDate: '2006-10-04',
    name: 'Death Note',
    voteAverage: 8.639,
    voteCount: 3684,
  },
  {
    adult: false,

    genreIds: [16, 35],
    idNumber: 42573,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'スラムダンク',
    overview:
      "Sakuragi Hanamichi is a junior high punk used to getting into fights and being rejected by girls but upon entering high school he meets the girl of his dreams, Haruko Akagi. He will do anything in order to win her heart including joining the school basketball team that is aiming to conquer the nation lead by Haruko's brother. The problem is that Sakuragi has never played basketball before and a freshman sensation is stealing the spotlight and Haruko's affection from him.",
    popularity: 104.324,
    firstAirDate: '1993-10-16',
    name: 'Slam Dunk',
    voteAverage: 8.637,
    voteCount: 811,
  },

  {
    adult: false,

    genreIds: [18],
    idNumber: 124834,
    originCountry: ['GB'],
    originalLanguage: 'en',
    originalName: 'Heartstopper',
    overview:
      'Teens Charlie and Nick discover their unlikely friendship might be something more as they navigate school and young love in this coming-of-age series.',
    popularity: 63.198,
    firstAirDate: '2022-04-22',
    name: 'Heartstopper',
    voteAverage: 8.634,
    voteCount: 1090,
  },
  {
    adult: false,

    genreIds: [16, 10759, 35, 10765],
    idNumber: 45950,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'ハイスクールD×D',
    overview:
      "The story follows Issei Hyōdō, a dim-witted, lecherous second-year high school student who is killed by a girl on his first date ever. Issei is reincarnated as a devil, and from that day forward, he serves as an underling of Riasu, a high-level devil who is also the prettiest girl on Issei's campus.",
    popularity: 160.371,
    firstAirDate: '2012-01-06',
    name: 'High School D×D',
    voteAverage: 8.635,
    voteCount: 1673,
  },
  {
    adult: false,

    genreIds: [35, 18],
    idNumber: 68349,
    originCountry: ['KR'],
    originalLanguage: 'ko',
    originalName: '역도요정 김복주',
    overview:
      'A competitive swimmer crosses paths with his childhood friend, a rising weight lifting star, and realizes that she has a secret crush on his cousin.',
    popularity: 61.058,
    firstAirDate: '2016-11-16',
    name: 'Weightlifting Fairy Kim Bok-joo',
    voteAverage: 8.629,
    voteCount: 726,
  },
  {
    adult: false,

    genreIds: [16, 10759, 10765],
    idNumber: 46298,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'HUNTER×HUNTER',
    overview:
      "Twelve-year-old Gon Freecss one day discovers that the father he had always been told was dead was alive. His Father, Ging, is a Hunter — a member of society's elite with a license to go anywhere or do almost anything. Gon, determined to follow in his father's footsteps, decidNumberes to take the Hunter Examination and eventually find his father to prove himself as a Hunter in his own right. But on the way, he learns that there is more to becoming a Hunter than previously thought, and the challenges that he must face are considNumberered the toughest in the world.",
    popularity: 207.029,
    firstAirDate: '2011-10-02',
    name: 'Hunter x Hunter',
    voteAverage: 8.634,
    voteCount: 1514,
  },
  {
    adult: false,

    genreIds: [16, 10759, 10765],
    idNumber: 45790,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'ジョジョの奇妙な冒険',
    overview:
      'Follow the intergenerational feud between the Joestar Family and various forces of evil, the most prominent of which is Dio Brando and his followers.',
    popularity: 149.084,
    firstAirDate: '2012-10-06',
    name: "JoJo's Bizarre Adventure",
    voteAverage: 8.631,
    voteCount: 1257,
  },
  {
    adult: false,

    genreIds: [18, 10765, 10768],
    idNumber: 66433,
    originCountry: ['KR'],
    originalLanguage: 'ko',
    originalName: '달의 연인 - 보보경심 려',
    overview:
      'A story of a 25-year old Go Ha-jin who is transported back in time to the Goryeo Dynasty. She then wakes up in the body of Lady Hae-soo and finds herself amongst the ruling princes of the Wang Family.',
    popularity: 39.013,
    firstAirDate: '2016-08-29',
    name: 'Scarlet Heart: Ryeo',
    voteAverage: 8.627,
    voteCount: 461,
  },
  {
    adult: false,

    genreIds: [16, 35],
    idNumber: 100,
    originCountry: ['GB'],
    originalLanguage: 'en',
    originalName: 'I Am Not an Animal',
    overview:
      'I Am Not An Animal is an animated comedy series about the only six talking animals in the world, whose cosseted existence in a vivisection unit is turned upsidNumbere down when they are liberated by animal rights activists.',
    popularity: 38.346,
    firstAirDate: '2004-05-10',
    name: 'I Am Not an Animal',
    voteAverage: 8.63,
    voteCount: 777,
  },
  {
    adult: false,

    genreIds: [16, 35, 10765],
    idNumber: 62741,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: '神様はじめました',
    overview:
      'Nanami was just a normal high school girl down on her luck until a stranger’s lips marked her as the new Land God and turned her world upsidNumbere down. Now, she’s figuring out the duties of a deity with the help of Tomoe, a reformed fox demon who reluctantly becomes her familiar in a contract sealed with a kiss. The new responsibilities—and boys—are a lot to handle, like the crow demon masquerading as a gorgeous pop idNumberol and the adorable snake spirit who’s chosen the newly minted god to be his bridNumbere. As the headstrong Tomoe tries to whip her into shape, Nanami finds that love just might have cute, pointed fox ears. With romance in the air, will the human deity be able to prove herself worthy of her new title?',
    popularity: 46.729,
    firstAirDate: '2012-10-02',
    name: 'Kamisama Kiss',
    voteAverage: 8.627,
    voteCount: 804,
  },
  {
    adult: false,

    genreIds: [10751, 35, 10762],
    idNumber: 31356,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Big Time Rush',
    overview:
      'Four teenage friends move from Minneapolis to Los Angeles to form a potential chart-topping boy band after Kendall is inadvertently discovered by an eccentric record executive, Gustavo Rocque. As they seize this opportunity of a lifetime, these friends embark on an exciting comedy and music-filled journey to prove to themselves and their record label that they are serious about their new career choice.',
    popularity: 74.394,
    firstAirDate: '2009-11-28',
    name: 'Big Time Rush',
    voteAverage: 8.6,
    voteCount: 1573,
  },
  {
    adult: false,

    genreIds: [35, 10759, 16, 10765],
    idNumber: 57706,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'らんま½',
    overview:
      "Saotome Ranma, a teenage martial artist, and his father Genma travel to the 'cursed training ground' of Jusenkyo in China. There, despite the warnings of the Chinese guard, they fall into the cursed springs. From now on, whenever Ranma is doused in cold water, he turns in to a girl, and a cute, well-built red-head at that. Hot water changes him back into a man again, but only until the next time. To make matters worse, his father engages him to Tendo Akane, a girl who hates boys.",
    popularity: 125.537,
    firstAirDate: '1989-04-15',
    name: 'Ranma ½',
    voteAverage: 8.624,
    voteCount: 1211,
  },
  {
    adult: false,

    genreIds: [18, 10765, 9648],
    idNumber: 66732,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Stranger Things',
    overview:
      'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    popularity: 340.867,
    firstAirDate: '2016-07-15',
    name: 'Stranger Things',
    voteAverage: 8.623,
    voteCount: 16349,
  },
  {
    adult: false,

    genreIds: [16, 35, 18, 10759],
    idNumber: 42705,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'はじめの一歩',
    overview:
      "Makunouchi Ippo is an ordinary high school student in Japan. Since he spends most of his time away from school helping his mother run the family business, he doesn't get to enjoy his younger years like most teenagers. Always a target for bullying at school (the family fishing business grants him a distinct odor), Ippo's life is one of hardship. One of these after-school bullying sessions turns Ippo's life around for the better, as he is saved by a boxer named Takamura. He decidNumberes to follow in Takamura's footsteps and train to become a boxer, giving his life direction and purpose. Ippo's path to perfecting his pugilistic prowess is just beginning...",
    popularity: 142.498,
    firstAirDate: '2000-10-03',
    name: 'Fighting Spirit',
    voteAverage: 8.624,
    voteCount: 880,
  },
  {
    adult: false,

    genreIds: [35, 18],
    idNumber: 62914,
    originCountry: ['ES'],
    originalLanguage: 'ca',
    originalName: 'Merlí',
    overview:
      'He’s surly, unorthodox, unapologetically blunt, and he’s about to change your life. Meet the new philosophy teacher, Merlí, who will help his students view the world in a whole new light, both in and out of the classroom.',
    popularity: 48.414,
    firstAirDate: '2015-09-14',
    name: 'Merlí',
    voteAverage: 8.621,
    voteCount: 1008,
  },
  {
    adult: false,

    genreIds: [18],
    idNumber: 1398,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'The Sopranos',
    overview:
      "The story of New Jersey-based Italian-American mobster Tony Soprano and the difficulties he faces as he tries to balance the conflicting requirements of his home life and the criminal organization he heads. Those difficulties are often highlighted through his ongoing professional relationship with psychiatrist Jennifer Melfi. The show features Tony's family members and Mafia associates in prominent roles and story arcs, most notably his wife Carmela and his cousin and protégé Christopher Moltisanti.",
    popularity: 273.35,
    firstAirDate: '1999-01-10',
    name: 'The Sopranos',
    voteAverage: 8.619,
    voteCount: 2352,
  },
  {
    adult: false,

    genreIds: [35, 18],
    idNumber: 97186,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Love, Victor',
    overview:
      'Victor is a new student at Creekwood High School on his own journey of self-discovery, facing challenges at home, adjusting to a new city, and struggling with his sexual orientation. When it all seems too much, he reaches out to Simon to help him navigate the ups and downs of high school.',
    popularity: 66.932,
    firstAirDate: '2020-06-17',
    name: 'Love, Victor',
    voteAverage: 8.618,
    voteCount: 1490,
  },
  {
    adult: false,

    genreIds: [10759, 16, 18],
    idNumber: 89456,
    originCountry: ['US'],
    originalLanguage: 'en',
    originalName: 'Primal',
    overview:
      'A caveman forms a bond with a dinosaur as they struggle to survive in a hostile world.',
    popularity: 41.014,
    firstAirDate: '2019-10-08',
    name: 'Primal',
    voteAverage: 8.618,
    voteCount: 1277,
  },
  {
    adult: false,

    genreIds: [16, 35, 9648],
    idNumber: 82739,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: '青春ブタ野郎はバニーガール先輩の夢を見ない',
    overview:
      "Puberty Syndrome—a rumored, mysterious syndrome that only affects those in their puberty. For example, a bunny girl suddenly appeared in front of Sakuta Azusagawa. The bunny girl's real idNumberentity is Mai Sakurajima, a teenage celebrity who is currently an inactive high school senior. For some reason, her charming figure does not reflect in the eyes of others. In the course of revealing the mystery behind this phenomenon, Sakuta begins to explore his feelings towards Mai. Set in a city where the skies and seas shine, Sakuta unfolds the meaning behind his bizarre encounters on women with the saidNumber syndrome.",
    popularity: 63.634,
    firstAirDate: '2018-10-04',
    name: 'Rascal Does Not Dream of Bunny Girl Senpai',
    voteAverage: 8.618,
    voteCount: 1071,
  },
  {
    adult: false,

    genreIds: [16, 10759, 10765],
    idNumber: 114410,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: 'チェンソーマン',
    overview:
      'Denji has a simple dream—to live a happy and peaceful life, spending time with a girl he likes. This is a far cry from reality, however, as Denji is forced by the yakuza into killing devils in order to pay off his crushing debts. Using his pet devil Pochita as a weapon, he is ready to do anything for a bit of cash.',
    popularity: 120.442,
    firstAirDate: '2022-10-12',
    name: 'Chainsaw Man',
    voteAverage: 8.617,
    voteCount: 1315,
  },
  {
    adult: false,

    genreIds: [18, 35, 10765],
    idNumber: 108261,
    originCountry: ['KR'],
    originalLanguage: 'ko',
    originalName: '철인왕후',
    overview:
      "In the modern age, Jang Bong-hwan is a chef who works for the country's top politicians at the Blue House. He has a free spirit, but he one day finds himself in the body of Queen Cheorin in the Joseon period.",
    popularity: 37.629,
    firstAirDate: '2020-12-12',
    name: 'Mr. Queen',
    voteAverage: 8.61,
    voteCount: 335,
  },
  {
    adult: false,

    genreIds: [16, 9648, 35],
    idNumber: 95269,
    originCountry: ['JP'],
    originalLanguage: 'ja',
    originalName: '地縛少年花子くん',
    overview:
      'First year high school student and occultist, Nene Yashiro summons "Hanako-san of the Toilet" to grant her romantic wishes. She ends up Hanako\'s spiritual assistant, helping him destroy supernatural beings and change rumors to balance the spirit and human worlds. Along the way, Nene learns about her connection to the spirit world and the dark secrets regarding Hanako\'s past.',
    popularity: 37.53,
    firstAirDate: '2020-01-10',
    name: 'Toilet-Bound Hanako-kun',
    voteAverage: 8.617,
    voteCount: 665,
  },
];
