export default {
  ACCESS_TOKEN_BACKOFFICE: 'ACCESS_TOKEN_BACKOFFICE',
  REFRESH_TOKEN_BACKOFFICE: 'REFRESH_TOKEN_BACKOFFICE',
  ACCESS_TOKEN_CLIENT: 'ACCESS_TOKEN_CLIENT',
  REFRESH_TOKEN_CLIENT: 'REFRESH_TOKEN_CLIENT',
};
